### ISSUE TITLE
TypeError: Cannot read property 'single' of undefined

### ISSUE THREAD

**Issue by senxiaoxing** [pantsPoi/Spruche#11] opened 2018-02-09 09:15 UTC
> spruche@0.1.1 start E:\workNode\Blog\Spruche
> node --harmony ./bin/www

E:\workNode\Blog\Spruche\routes\admin.js:23
const friendImgUpload = upload.friendImgUpload.single('friendhead');
                                               ^

TypeError: Cannot read property 'single' of undefined
    at Object.<anonymous> (E:\workNode\Blog\Spruche\routes\admin.js:23:48)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\workNode\Blog\Spruche\app.js:17:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spruche@0.1.1 start: `node --harmony ./bin/www `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spruche@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JasonYang\AppData\Roaming\npm-cache\_logs\2018-02-09T09_08_03_940Z-debug.log

**Comment by IceEnd** [comment] 2018-02-09 13:40
能把node版本发一下吗？

**Comment by senxiaoxing** [comment] 2018-02-10 04:32
node 8.9.4




| |
杨森
邮箱：13554342109@163.com
|

签名由 网易邮箱大师 定制

在2018年02月09日 21:40，Alchemy 写道：

能把node版本发一下吗？

**Comment by lovelifeloveyou** [comment] 2018-04-13 02:57
我也是报相同的错误，显示TypeError: Cannot read property 'single' of undefined

**Comment by IceEnd** [comment] 2018-04-22 13:21
Duplicate of #12

**Closed as completed** 2018-06-06 05:58 UTC
